#!/bin/bash

npm install --save-dev \
@rollup/plugin-commonjs \
@rollup/plugin-json \
@rollup/plugin-node-resolve \
@types/jest \
@typescript-eslint/eslint-plugin \
@typescript-eslint/parser \
concurrently \
eslint \
jest \
prettier \
rollup \
rollup-plugin-typescript2 \
ts-jest \
typescript \

